<h1><center>Tweets from Twitter re. COVID</center></h1?

- Playing around with parameters for twitter
- df does not include "since_date" & "until_date" 

- https://towardsdatascience.com/how-to-scrape-tweets-from-twitter-59287e20f0f1
- https://github.com/Etanangc8/TwitterBot/blob/master/TwitterScraper/GetOldTweets3_Twitter_Scraper.ipynb
- https://github.com/Mottl/GetOldTweets3
- https://bhaskarvk.github.io/2015/01/how-to-use-twitters-search-rest-api-most-effectively./

In [1]:
!pip install GetOldTweets3

Collecting GetOldTweets3
  Downloading GetOldTweets3-0.0.11-py3-none-any.whl (13 kB)
Requirement already satisfied: lxml>=3.5.0 in /Users/EderlynT/opt/anaconda3/envs/dsi/lib/python3.7/site-packages (from GetOldTweets3) (4.5.0)
Collecting pyquery>=1.2.10
  Downloading pyquery-1.4.1-py2.py3-none-any.whl (22 kB)
Collecting cssselect>0.7.9
  Downloading cssselect-1.1.0-py2.py3-none-any.whl (16 kB)
Installing collected packages: cssselect, pyquery, GetOldTweets3
Successfully installed GetOldTweets3-0.0.11 cssselect-1.1.0 pyquery-1.4.1

In [3]:
import GetOldTweets3 as got
import pandas as pd
import time

In [7]:
# Parameters: (text query you want to search), (max number of most recent tweets to pull from)
def text_query_to_csv(text_query, count):
    
    # Creation of query object
    tweetCriteria = got.manager.TweetCriteria().setQuerySearch(text_query).setSince(since_date).setUntil(until_date).setMaxTweets(count)

    # Creation of list that contains all tweets
    tweets = got.manager.TweetManager.getTweets(tweetCriteria)

    # Creating list of chosen tweet data
    text_tweets = [[tweet.date, tweet.text] for tweet in tweets]    

    # Creation of dataframe from tweets
    tweets_df = pd.DataFrame(text_tweets, columns = ['Datetime', 'Text'])

    # Converting tweets dataframe to csv file
    tweets_df.to_csv('{}-{}k-tweets.csv'.format(text_query, int(count/1000)), sep=',')
    
    time.sleep(3)

In [8]:
# Input search query to scrape tweets and name csv file
# Max recent tweets pulls x amount of most recent tweets from that user
text_query = 'covid'
count = 2000

# Calling function to query X amount of relevant tweets and create a CSV file
text_query_to_csv(text_query, count)

In [10]:
tweets = pd.read_csv('./covid-2k-tweets.csv')
tweets.head()

,Unnamed: 0,Datetime,Text
0,0,2020-04-29 23:59:59+00:00,tive covid 19 e é uma das piores sensações q e...
1,1,2020-04-29 23:59:59+00:00,@SandraHassan10 : #gc fait de grands pas dans ...
2,2,2020-04-29 23:59:59+00:00,When babies are born at the hospital my dad wo...
3,3,2020-04-29 23:59:58+00:00,Brendon Rearick & Kevin Carr with Mike Boyle S...
4,4,2020-04-29 23:59:58+00:00,Also flockimmunitet depends on clinical qualit...

In [ ]:
# text_query = 'covid'
# since_date = '2020-03-01'
# until_date = '2020-04-30'
# count = 1000

# # Creation of query object
# tweetCriteria = got.manager.TweetCriteria().setQuerySearch(text_query)
# .setSince(since_date).setUntil(until_date).setMaxTweets(count)

# # Creation of list that contains all tweets
# tweets = got.manager.TweetManager.getTweets(tweetCriteria)

# # Creating list of chosen tweet data
# text_tweets = [[tweet.date, tweet.text] for tweet in tweets]

In [11]:
tweets.tail()

,Unnamed: 0,Datetime,Text
1995,1995,2020-04-29 23:55:05+00:00,La empresa de Alimentos Polar considera que re...
1996,1996,2020-04-29 23:55:05+00:00,Increase in current testing capacity from 6000...
1997,1997,2020-04-29 23:55:05+00:00,A huge shoutout to the men who step to the rol...
1998,1998,2020-04-29 23:55:05+00:00,Lo bueno y destacable de esta cuarentena es qu...
1999,1999,2020-04-29 23:55:05+00:00,Michoacán alista la distribución de apoyo alim...

In [13]:
tweets.isnull().sum()

Unnamed: 0    0
Datetime      0
Text          1
dtype: int64

In [18]:
tweets[tweets['Text'].duplicated() == True]

,Unnamed: 0,Datetime,Text
321,321,2020-04-29 23:59:09+00:00,TAFE NSW offers more fee free courses online f...
334,334,2020-04-29 23:59:07+00:00,Kongo central/Covid -19 : Isabelle Nkusu veill...
507,507,2020-04-29 23:58:43+00:00,The economic impacts of COVID-19 may have a hi...
613,613,2020-04-29 23:58:25+00:00,Not
674,674,2020-04-29 23:58:17+00:00,Chloroquine (CHQ) and Hydroxychloroquine (HCQ)...
703,703,2020-04-29 23:58:11+00:00,To put it simply @realDonaldTrump deliberate g...
764,764,2020-04-29 23:58:01+00:00,From quick meals that can be picked up to food...
904,904,2020-04-29 23:57:44+00:00,ayo patuhi protokol kesehatan demi mencegah Co...
931,931,2020-04-29 23:57:40+00:00,Ex-Republican blasts ‘elitist punk’ Jared Kush...
940,940,2020-04-29 23:57:40+00:00,"Top story: @JasonSCampbell: 'Ben Shapiro: ""If ..."
944,944,2020-04-29 23:57:39+00:00,ayo patuhi protokol kesehatan demi mencegah Co...
993,993,2020-04-29 23:57:31+00:00,The economic impacts of COVID-19 may have a hi...
1091,1091,2020-04-29 23:57:17+00:00,Chiron author Stefano Carpini discusses his ne...
1109,1109,2020-04-29 23:57:14+00:00,Ex-Republican blasts ‘elitist punk’ Jared Kush...
1126,1126,2020-04-29 23:57:12+00:00,Coronavirus live news: more cases of ‘Covid-li...
1150,1150,2020-04-29 23:57:10+00:00,Webinar: Género y ruralidad en tiempos de #COV...
1166,1166,2020-04-29 23:57:07+00:00,From quick meals that can be picked up to food...
1265,1265,2020-04-29 23:56:54+00:00,when we reached out to Ian Anderson @jethrotul...
1295,1295,2020-04-29 23:56:50+00:00,Two men in Georgia drank disinfectants in effo...
1324,1324,2020-04-29 23:56:45+00:00,The economic impacts of COVID-19 may have a hi...
1438,1438,2020-04-29 23:56:29+00:00,Aprueban diputados que venta de inmuebles sea ...
1452,1452,2020-04-29 23:56:27+00:00,when we reached out to Ian Anderson @jethrotul...
1491,1491,2020-04-29 23:56:21+00:00,The economic impacts of COVID-19 may have a hi...
1539,1539,2020-04-29 23:56:13+00:00,Elon Musk's COVID-19 meltdown: 'Give people ba...
1586,1586,2020-04-29 23:56:06+00:00,when we reached out to Ian Anderson @jethrotul...
1604,1604,2020-04-29 23:56:03+00:00,Over 70% of tested inmates in federal prisons ...
1644,1644,2020-04-29 23:55:58+00:00,NYC teacher dies from COVID-19 after she was d...
1693,1693,2020-04-29 23:55:51+00:00,The economic impacts of COVID-19 may have a hi...
1721,1721,2020-04-29 23:55:47+00:00,Webinar: Género y ruralidad en tiempos de #COV...
1780,1780,2020-04-29 23:55:39+00:00,COVID-19: altera la ofensiva del Pentágono con...
1814,1814,2020-04-29 23:55:33+00:00,#RDC-#Covid19: Le Premier Ministre a échangé a...
1894,1894,2020-04-29 23:55:21+00:00,Coronavirus live news: more cases of ‘Covid-li...
1912,1912,2020-04-29 23:55:18+00:00,#QuedateEnCasa Declaración de Prensa de @drodr...